### ISSUE TITLE
Nuxt Icon module

### ISSUE THREAD

**Issue by justserdar** [nuxt-ui-pro/saas#57]
Platform: Win10/Mac OS

Started happening after @nuxt/icon got updated to v1.5.3 tto fix url scheme install error.
However ever since I've gotten that moment the following errors even after recloning & clean install:

`
 WARN  [Icon] loading icon heroicons:arrow-right-20-solid timed out after 500ms
 WARN  [Icon] loading icon heroicons:chevron-down-20-solid timed out after 500ms
 WARN  [Icon] loading icon heroicons:hashtag-20-solid timed out after 500ms
 WARN  [Icon] loading icon heroicons:hashtag-20-solid timed out after 500ms
 WARN  [Icon] loading icon heroicons:hashtag-20-solid timed out after 500ms
 WARN  [Icon] loading icon heroicons:exclamation-triangle timed out after 500ms
 WARN  [Icon] loading icon heroicons:hashtag-20-solid timed out after 500ms
 WARN  [Icon] loading icon heroicons:clipboard-document timed out after 500ms
 WARN  [Icon] loading icon heroicons:hashtag-20-solid timed out after 500ms
 WARN  [Icon] loading icon heroicons:hashtag-20-solid timed out after 500ms
 WARN  [Icon] loading icon heroicons:hashtag-20-solid timed out after 500ms
 WARN  [Icon] loading icon heroicons:hashtag-20-solid timed out after 500ms (repeated 7 times)
`

Anyone else having this issue?

**Comment by benjamincanac** [comment]
It should have been fixed in `@nuxt/icon` https://github.com/nuxt/icon/releases/tag/v1.5.5. Can you try to refresh your lock?

**Comment by justserdar** [comment]
Still not sadly:
- Removed @nuxt/icon locally.
- Changed out my lock

Output
```
ℹ Nuxt Icon server bundle mode is set to local                                                                         9:21:28 PM
✔ Nuxt Icon discovered local-installed 3 collections: heroicons, simple-icons, vscode-icons                            9:21:33 PM
ℹ Running with compatibility version 4                                                                                 9:21:34 PM
ℹ Tailwind Viewer: http://localhost:3000/_tailwind/                                                   nuxt:tailwindcss 9:21:34 PM
ℹ Re-optimizing dependencies because lockfile has changed                                                              9:21:37 PM
✔ Vite client built in 353ms                                                                                           9:21:37 PM
✔ Vite server built in 4456ms                                                                                          9:21:41 PM
✔ Nuxt Nitro server built in 8748 ms                                                                             nitro 9:21:53 PM
ℹ Vite client warmed up in 14524ms                                                                                     9:22:07 PM
ℹ Vite server warmed up in 19595ms                                                                                     9:22:12 PM
✔ Vite server hmr 38 files in 9165.007ms
 WARN  [Icon] loading icon heroicons:bars-3-20-solid timed out after 500ms
 WARN  [Icon] loading icon heroicons:arrow-up-right-20-solid timed out after 500ms
 WARN  [Icon] loading icon heroicons:arrow-up-right-20-solid timed out after 500ms
 WARN  [Icon] loading icon simple-icons:github timed out after 500ms
 WARN  [Icon] loading icon heroicons:arrow-top-right-on-square-20-solid timed out after 500ms
```

**Comment by benjamincanac** [comment]
It's weird because it fixed it for me. Maybe you can try a fresh install? I've released `@nuxt/ui-pro@1.4.4` / `@nuxt/ui@2.18.7` today that includes latest `@nuxt/icon`.

**Comment by justserdar** [comment]
Updating `@nuxt/ui-pro@1.4.3` -> 1.4.4 fixed it for me.
Thanks for so replying so fast by the way!
